version: '3'

networks:
  efrenvalfonso-net:
    external: true

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: efrenvalfonso_net
      MYSQL_ROOT_PASSWORD: i^1bUb9!fW9h
    volumes:
      - db-data:/var/lib/mysql
  web:
    build: .
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data: